### ISSUE TITLE
You're storing Credict Cards information on the server

### ISSUE THREAD

**Issue by mariorodriguespt** [awatson1978/payment-subscription#2]
The line `Meteor.call('createNewSubscription', formData` is simply evil, you have to use the stripe token.

**Comment by awatson1978** [comment]
1.  Actually, that's a deprecated call, and if you search 'createNewSubscription' you'll see that there's no corresponding meteor method, and it dumps into null.
2.  When that method did exist, there was no writing to Mongo and persisting the call; it was for accessing the server side Stripe SDK.
3.  It's extremely rude to post to people's code they're contributing for your benefit and tell them that it's evil.
4.  I don't see you doing anything constructive like submitting a pull request.  Just whining and being rude.
5.  So shove off.

**Comment by mariorodriguespt** [comment]
LOL

Of course I'll disappear from this repo after just a stupid response.
